---
- name: Remove GUI
  win_feature:
   name: Server-Gui-Shell, Server-Gui-Mgmt-Infra
   state: absent
  when:
   - ansible_os_family == "Windows"
   - ansible_distribution_major_version != "10"

  notify:
   - Reboot

