---
  - name: "Download 7-Zip msi file"
    win_get_url: 
      url: http://www.7-zip.org/a/7z1700-x64.msi
      dest: c:\Users\Public\Downloads\7z1700-x64.msi
      force: no
  - name: "Install 7-zip MSI"
    win_msi:
      path: c:\Users\Public\Downloads\7z1700-x64.msi
      state: present
      wait: true
