---
# tasks file for aws.bastionhost
- name: Create bastionhost inbound rules.
  ec2_group:
    aws_secret_key: "{{ aws_secret_key.stdout }}"
    aws_access_key: "{{ aws_access_key.stdout }}"
    region: "{{ vpc.region }}"
    description: "{{ securitygroups_bastionhost.tags.Name }} inbound rules"
    name: "{{ securitygroups_bastionhost.name }}"
    rules: "{{ securitygroups_bastionhost.rules }}"
    vpc_id: "{{ vpc_id_fact }}"
  register: bastionhost_inbound_results

- name: Tag bastionhost inbound traffic rules.
  ec2_tag:
    aws_secret_key: "{{ aws_secret_key.stdout }}"
    aws_access_key: "{{ aws_access_key.stdout }}"
    region: "{{ vpc.region }}"
    resource: "{{ bastionhost_inbound_results.group_id }}"
    state: present
    tags: "{{ securitygroups_bastionhost.tags }}"

- name: Get subnet ID based on subnet variable in ec2_bastionhost dictionary.
  ec2_vpc_subnet_facts:
    aws_secret_key: "{{ aws_secret_key.stdout }}"
    aws_access_key: "{{ aws_access_key.stdout }}"
    region: "{{ vpc.region }}"
    filters:
      "tag:Name": "{{ ec2_bastionhost.subnet }}"
  register: vpc_subnet_facts

# tasks file for aws.iam
- name: Create Bastion IAM role.
  iam:
    aws_secret_key: "{{ aws_secret_key.stdout }}"
    aws_access_key: "{{ aws_access_key.stdout }}"
    region: "{{ vpc.region }}"
    name: "{{ iam_bastionhost.name }}"
    iam_type: "{{ iam_bastionhost.iam_type }}"
    state: "{{ iam_bastionhost.state }}"
  register: iam_results
  
- name: Pause when new IAM roles are created.
  pause:
    seconds: 7
  when: iam_results.changed
  
- name: Create bastionhost instance.
  ec2:
    aws_secret_key: "{{ aws_secret_key.stdout }}"
    aws_access_key: "{{ aws_access_key.stdout }}"
    region: "{{ vpc.region }}"
    assign_public_ip: "{{ ec2_bastionhost.assign_public_ip }}"
    count_tag:
      Name: "{{ ec2_bastionhost.instance_tags.Name }}"
    exact_count: "{{ ec2_bastionhost.exact_count }}"
    instance_profile_name: "{{ iam_bastionhost.name }}"
    group: "{{ ec2_bastionhost.groups }}"
    instance_tags: "{{ ec2_bastionhost.instance_tags }}"
    image: "{{ vpc.image }}"
    instance_type: "{{ ec2_bastionhost.instance_type }}"
    keypair: "{{ ec2_bastionhost.keypair }}"
    source_dest_check: no
    vpc_subnet_id: "{{ vpc_subnet_facts.subnets|map(attribute='id')|list|first }}"
    wait: "{{ ec2_bastionhost.wait }}"
  register: bastionhost_instance_results

- name: Allocating elastic IP to instance
  ec2_eip:
    aws_secret_key: "{{ aws_secret_key.stdout }}"
    aws_access_key: "{{ aws_access_key.stdout }}"
    in_vpc: yes
    reuse_existing_ip_allowed: yes
    state: present
    region: "{{ vpc.region }}"
    instance_id: "{{ bastionhost_instance_results.instance_ids[0] }}"
  when: "bastionhost_instance_results.instance_ids[0] is defined"
  register: instance_eip
- debug: var=instance_eip.public_ip

- name: Create bastionhost SSH inbound rules for internal instances.
  ec2_group:
    aws_secret_key: "{{ aws_secret_key.stdout }}"
    aws_access_key: "{{ aws_access_key.stdout }}"
    region: "{{ vpc.region }}"
    description: "{{ securitygroups_bastionhost_internal.tags.Name }} SSH rules."
    name: "{{ securitygroups_bastionhost_internal.name }}"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: "{{ bastionhost_instance_results.tagged_instances.0.private_ip }}/32"
    vpc_id: "{{ vpc_id_fact }}"
  register: bastionhost_inbound_internal_results

- name: Tag bastionhost SSH inbound rules for internal instancensn.
  ec2_tag:
    aws_secret_key: "{{ aws_secret_key.stdout }}"
    aws_access_key: "{{ aws_access_key.stdout }}"
    region: "{{ vpc.region }}"
    resource: "{{ bastionhost_inbound_internal_results.group_id }}"
    state: present
    tags: "{{ securitygroups_bastionhost_internal.tags }}"


- name: Set public DNS fact.
  set_fact:
    bastion_public_dns_name: "{{ bastionhost_instance_results.tagged_instances.0.public_dns_name }}"

- name: Print public IP address.
  debug:
    msg: "bastionhost public DNS: {{ bastion_public_dns_name }}"
